In [1]:
# -*- coding : utf-8 -*-
import pandas as pd
import numpy as np

In [8]:
# NOTE
# DataFrame과 Series 사이에서 연산할 때 인덱스와 열의 순서는 비슷하게 유지된다.
# DataFrame과 Series 사이의 연산은 NumPy의 1차원 배열과 2차원 배열의 연산과 비슷하다.
rand = np.random.RandomState(42)
A = rand.randint(10, size = (3, 4))
print(A, '\n')
print(A - A[0])

[[6 3 7 4]
 [6 9 2 6]
 [7 4 3 7]] 

[[ 0  0  0  0]
 [ 0  6 -5  2]
 [ 1  1 -4  3]]


In [15]:
df = pd.DataFrame(A, columns=list('QRST'))
print(df, '\n')
print(df - df.iloc[0], '\n')

# NOTE : 열 방향 연산을 하고자 하면 pandas 산술 연산자에 axis 옵션을 추가하면 된다.
print(df.subtract(df['R'], axis = 0), '\n')

# NOTE : 두 요소 간의 인덱스를 자동으로 맞춤.
halfrow = df.iloc[0, ::2]
print(halfrow, '\n')
print(df - halfrow)

   Q  R  S  T
0  6  3  7  4
1  6  9  2  6
2  7  4  3  7 

   Q  R  S  T
0  0  0  0  0
1  0  6 -5  2
2  1  1 -4  3 

   Q  R  S  T
0  3  0  4  1
1 -3  0 -7 -3
2  3  0 -1  3 

Q    6
S    7
Name: 0, dtype: int32 



     Q   R    S   T
0  0.0 NaN  0.0 NaN
1  0.0 NaN -5.0 NaN
2  1.0 NaN -4.0 NaN
