In [7]:
# -*- coding : utf-8 -*-
import numpy as np

In [15]:
# NOTE: 팬시 인덱싱
# 팬시 인덱싱 : 단일 스칼라 대신 인덱스 배열을 반환
#             이로써 복잡한 배열 값의 하위 집합에 매우 빠르게 접근하여 수정가능
rand = np.random.RandomState(42)
x = rand.randint(100, size = 10)
x

array([51, 92, 14, 71, 60, 20, 82, 86, 74, 74])

In [11]:
# NOTE : 세 개의 다른 요소에 접근하고자 할 때
print([x[3], x[7], x[2]])

# NOTE : 인덱스의 단일 리스트나 배열을 전달
ind = [3, 7, 4]
print(x[ind])

[71, 86, 14]
[71 86 60]


In [13]:
# NOTE : 결과의 형상이 대상 배열의 형상이 아니라 인덱스 배열의 형상을 반영
ind = np.array([[3, 7],
                [4, 5]])
print(x[ind])

[[71 86]
 [60 20]]


In [14]:
y = np.arange(12).reshape((3, 4))
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [23]:
row = np.array([0, 1, 2])
col = np.array([2, 1, 3])
print(y[row, col], '\n')
# output : [2  5 11]
# NOTE : 결과의 첫 번째 값은 y[0, 2], 두 번째 값은 y[1,1], 세 번째 값은 y[2, 3]

print(y[row[:,np.newaxis], col], '\n')
print(row[:, np.newaxis] * col)

# NOTE : 팬시 인덱싱을 사용하면 인덱싱 대상 배열의 형상이 아니라 
#        브로드캐스팅 된 인덱스의 형상을 반영

[ 2  5 11] 

[[ 2  1  3]
 [ 6  5  7]
 [10  9 11]] 

[[0 0 0]
 [2 1 3]
 [4 2 6]]
