In [1]:
# -*- coding : utf-8 -*-
import numpy as np

In [7]:
# NOTE : 결합 인덱싱
# 결합 인덱싱 : 배열값에 접근하고 수정하기에 매우 유연한 연산을 수행하게 해줌.
x = np.arange(12).reshape((3, 4))
row = np.array([0, 1, 2])
col = np.array([2, 1, 3])

print(x)
# NOTE : 팬시 인덱스와 단순 인덱스를 결합할 수 있다.
x[2, [2, 0, 1]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [6]:
# NOTE : 팬시 인덱싱과 마스킹을 결합할 수 있다.
mask = np.array([1, 0, 1, 0], dtype = bool)
x[row[:, np.newaxis], mask]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])