In [1]:
# -*- coding : utf-8 -*-
import numpy as np

In [6]:
# NOTE : 팬시 인덱싱으로 값 변경하기
x = np.arange(10)
ind = np.array([2, 1, 8, 4])
x[ind] = 99
x[ind] -= 10
print(x)

[ 0 89 89  3 89  5  6  7 89  9]


In [16]:
y = np.zeros(10)
y[[0, 0]] = [4 ,6]
print(y)

# output : [6. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
# NOTE : y[0] = 4가 할당되고 그 다음 y[0] = 6이 할당 되었다.

[6. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [17]:
ind = [2, 3, 3, 4, 4, 4]
y[ind] += 1
print(y)

# output : [6. 0. 1. 1. 1. 0. 0. 0. 0. 0.]

[6. 0. 1. 1. 1. 0. 0. 0. 0. 0.]


In [18]:
# NOTE
# at : 지정한 값을 가진 특정 인덱스에 해당 연산자를 즉시 적용함.
z = np.zeros(10)
np.add.at(z, ind, 1)
print(z)

# output : [0. 0. 1. 2. 3. 0. 0. 0. 0. 0.]

[0. 0. 1. 2. 3. 0. 0. 0. 0. 0.]
