In [1]:
# -*- coding : utf-8 -*-
import numpy as np

In [7]:
# NOTE : NumPy 정렬
# np.sort는 기본적으로 퀵 정렬 알고리즘을 사용

x = np.array([2, 1, 4, 3, 5])
print(np.sort(x))

[1 2 3 4 5]


In [9]:
# NOTE : 정렬된 요소의 인덱스를 반환
ind = np.argsort(x)
ind

array([1, 0, 3, 2, 4], dtype=int64)

In [15]:
# NOTE : 행이나 열 기준으로 정렬
rand = np.random.RandomState(42)
y  = rand.randint(0, 10, (4, 6))
print(y)

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


In [18]:
# NOTE : 각 열을 정렬
print(np.sort(y, axis = 0), '\n')

# NOTE : 각 행을 정렬
print(np.sort(y, axis = 1))

[[2 1 4 0 1 5]
 [5 2 5 4 3 7]
 [6 3 7 4 6 7]
 [7 6 7 4 9 9]] 

[[3 4 6 6 7 9]
 [2 3 4 6 7 7]
 [1 2 4 5 7 7]
 [0 1 4 5 5 9]]


In [23]:
# NOTE
# 부분정렬 : 파티션 나누기

# NOTE
# partition : 배열과 숫자 K를 취해 새로운 배열 반환
#             반환된 파티션의 왼쪽에는 K개의 가장 작은 값, 나머지 오른쪽에는 나머지 값을 임의의 순서로 채워짐.

x = np.array([7, 2, 3, 1, 6, 5, 4])
np.partition(x, 3)

array([2, 1, 3, 4, 6, 5, 7])