In [2]:
import numpy as np

In [3]:
np.array([1, 2, 3, 4], dtype = 'float32')

array([1., 2., 3., 4.], dtype=float32)

In [4]:
np.array([3.14, 1, 5, 6.26], dtype = int)

array([3, 1, 5, 6])

In [6]:
# NOTE : 정수형 배열을 실수형 배열로 변환
np.array([1, 2, 3, 4], dtype = 'float32')

array([1., 2., 3., 4.], dtype=float32)

In [7]:
# NOTE : 리스트를 중첩하면 다차원 배열이 됨.
np.array([range(rep, rep+3) for rep in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [8]:
# NOTE : 0으로 가득찬 길이 10의 정수 배열만들기.
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
# NOTE : 1로 가득채운 3x5 부동 소수점 배열 만들기.
np.ones((3, 5), dtype = float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
# NOTE : 3.14로 가득채운 3x5배열 만들기.
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [12]:
# NOTE : 선형 수열로 채운 배열 만들기
#        0에서 시작해 2씩 더해 20까지 채움.
#        내장함수인 range()와 유사함.
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
# NOTE : 0과 1사이에 일정한 간격을 가진 다섯 개의 값으로 채운 배열 만들기
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [15]:
# NOTE : 균등하게 분포된 3x3 배열 만들기
#        0과 1사이의 난수로 채움.
np.random.random((3,3))

array([[0.73102469, 0.52180418, 0.21939753],
       [0.56698382, 0.03265219, 0.70705666],
       [0.49084667, 0.20798622, 0.38943055]])

In [16]:
# NOTE : 정규 분포 (평균 = 0, 표준편차 = 1)의 난수로 채운 3x3 배열 만들기.
np.random.normal(0, 1, (3, 3))

array([[-0.18589386,  0.54524083,  0.07597408],
       [-1.36461694,  0.48965771,  0.56517709],
       [-1.75037642, -0.49246833,  1.70187634]])

In [17]:
# NOTE : 3x3 단위행렬 만들기
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
# NOTE : 세 개의 정수를 가지는 초기화되지 않은 배열 만들기
#        값은 해당 메모리 위치에 이미 존재하고 있는 값으로 채움.
np.empty(3)

array([1., 1., 1.])