In [3]:
import numpy as np

# NOTE : 재현 가능성을 위한 시드 값
np.random.seed(0)
x1 = np.random.randint(10, size = 6) # NOTE : 1차원 배열
x2 = np.random.randint(10, size = (3, 4)) # NOTE : 2차원 배열
x3 = np.random.randint(10, size = (3, 4, 5)) # NOTE : 3차원 배열

In [5]:
# NOTE : 각 배열은 ndim(차원의 개수), shape(각 차원의 크기), size(전체배열 크기)를 가지고 있다.

print("x3 ndim : ", x3.ndim)
print("x3 shape : ", x3.shape)
print("x3 size : ", x3.size)
print("x3 dtype : ", x3.dtype)

x3 ndim :  3
x3 shape :  (3, 4, 5)
x3 size :  60
x3 dtype :  int32


In [7]:
# NOTE : (itemsize) 각 배열 요소의 크기를 바이트 단위로 보여줌.
#        (nbytes) 배열의 전체 크기를 바이트 단위로 보여줌.
#        (nbytes = itemsize * size)
print("x3 itemsize : ", x3.itemsize, " bytes")
print("x3 nbytes : ", x3.nbytes, " bytes")

x3 itemsize :  4  bytes
x3 nbytes :  240  bytes


In [15]:
x1

array([5, 0, 3, 3, 7, 9])

In [10]:
for rep in x1:
    print(rep)

5
0
3
3
7
9


In [11]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [14]:
for o_rep in x2:
    for i_rep in o_rep:
        print(i_rep)

3
5
2
4
7
6
8
8
1
6
7
7


In [18]:
x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])