In [17]:
import numpy as np

x = np.arange(10)

np.random.seed(0)
x1 = np.random.randint(10, size = 6)
x2 = np.random.randint(10, size = (3, 4))
x3 = np.random.randint(10, size = (3, 4, 5))

x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [5]:
# NOTE : 배열변수[start, stop, step]
print(x[:5],'\n', x[5:],'\n', x[4:7],'\n', x[::2],'\n', x[1::2],'\n')

[0 1 2 3 4] 
 [5 6 7 8 9] 
 [4 5 6] 
 [0 2 4 6 8] 
 [1 3 5 7 9] 



In [6]:
print(x[::-1], '\n', x[5::-2])

[9 8 7 6 5 4 3 2 1 0] 
 [5 3 1]


In [15]:
# NOTE : 2개의 행, 3개의 열
x2[:2, :3]

array([[12,  5,  2],
       [ 7,  6,  8]])

In [14]:
# NOTE : 모든 행, 한 열 걸러 하나씩
x2[:3, ::2]

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [13]:
# NOTE : 역순정렬
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

In [19]:
# NOTE : x2의 첫 번째 열
x2[:, 0]

# NOTE : x2의 첫 번째 행
x2[0, :]

array([12,  5,  2,  4])

In [21]:
# NOTE : x2[0, :]과 동일
print(x2[0])

[12  5  2  4]
