In [3]:
import numpy as np

np.random.seed(0)
x1 = np.random.randint(10, size = 6)
x2 = np.random.randint(10, size = (3, 4))
x3 = np.random.randint(10, size = (3, 4, 5))

x2[0, 0] = 12

In [7]:
# NOTE : numpy에서의 배열 슬라이스는 사본(copy)이 아니라 뷰(view)이다.
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  5]
 [ 7  6]]


In [8]:
x2_sub[0, 0] = 99
print(x2_sub)
print(x2)

[[99  5]
 [ 7  6]]
[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [10]:
# NOTE : 배열의 사본 만들기
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [12]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)
print(x2)

[[42  5]
 [ 7  6]]
[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [13]:
# NOTE : 1차원 배열을 3x3배열로 재구조화 시킴.
x4 = np.arange(1, 10)
x4

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
grid = x4.reshape(3, 3)
grid

# NOTE : 이 코드가 동작하려면 초기 배열의 규모가 형상이 변경된 배열의 규모와 일치해야 한다.

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
x5 = np.array([1, 2, 3])

In [20]:
# NOTE : reshape를 이용한 행 벡터
x5 = x5.reshape(1,3)

array([[1, 2, 3]])