In [3]:
import numpy as np

x1 = np.arange(1,10)
x2 = np.array([1, 2, 3])

In [4]:
# NOTE : reshape 메소드를 이용한 행벡터
x2.reshape(1,3)

array([[1, 2, 3]])

In [5]:
# NOTE : newaxis 메소드를 이용한 행벡터
x2[np.newaxis, : ]

array([[1, 2, 3]])

In [6]:
# NOTE : reshape 메소드를 이용한 열벡터
x2.reshape(3, 1)

array([[1],
       [2],
       [3]])

In [7]:
# NOTE : newaxis 메소드를 이용한 열벡터
x2[ : , np.newaxis]

array([[1],
       [2],
       [3]])