In [15]:
import numpy as np

x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
z = np.array([99, 99, 99])
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

v = np.array([100, 100, 100])
h = np.array([[99], [99]])

In [3]:
# NOTE : 배열을 연결 시켜줌.
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [5]:
# NOTE : 두 개 이상의 배열도 연결시켜줌.
np.concatenate([x, y, z])

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

In [10]:
# NOTE : concatenate는 2차원 배열도 적용가능함.
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [16]:
# NOTE : 혼합된 차원의 배열 합치기
# np.vstack(vertical stack / 수직 스택), np.hstack(horizontal stack / 수평스택)
np.vstack([grid,v])

array([[  1,   2,   3],
       [  4,   5,   6],
       [100, 100, 100]])

In [18]:
np.hstack([grid, h])

array([[ 1,  2,  3, 99],
       [ 4,  5,  6, 99]])