In [31]:
# -*- coding : utf-8 -*-
%matplotlib inline

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
import os

sns.set()

In [34]:
# os.chdir('./Python-Practice/Python Practice from Windows/numpy/data')
print(os.getcwd())

data = pd.read_csv('Seattle2014.csv', engine='python')

D:\Programming\Python\Python-Practice\Python Practice from Windows\numpy\data


In [41]:
rainfall = data['PRCP'].values

# NOTE : 1 inch = 25.4mm => 10/254 inch = 1mm => 1/254 inch = 1/10 mm
inches = rainfall / 254 

In [49]:
rng = np.random.RandomState(0)
x = np.random.randint(10, size = (3, 4))
x

array([[4, 6, 1, 5],
       [6, 9, 2, 6],
       [2, 1, 6, 3]])

In [17]:
# NOTE : 비교연산자와 대응 ufunc
# == : np.equal
# != : np.not_equal
# < : np.less
# <= : np.less_equal
# > : np.greater
# >= : np.greater_equal

In [51]:
print(np.equal(x, 1))
print(np.not_equal(x, 1))

print(np.less(x, 5))
print(np.less_equal(x, 5))
print(np.greater(x, 5))
print(np.greater_equal(x, 5))

[[False False  True False]
 [False False False False]
 [False  True False False]]
[[ True  True False  True]
 [ True  True  True  True]
 [ True False  True  True]]
[[ True False  True False]
 [False False  True False]
 [ True  True False  True]]
[[ True False  True  True]
 [False False  True False]
 [ True  True False  True]]
[[False  True False False]
 [ True  True False  True]
 [False False  True False]]
[[False  True False  True]
 [ True  True False  True]
 [False False  True False]]


In [52]:
print(np.count_nonzero(np.less(x, 6)))
print(np.sum(np.less(x, 6)))
print(np.sum(np.less(x, 6), axis = 1)) # NOTE : 각 행에 6보다 작은 값의 갯수
print(np.sum(np.less(x ,6), axis = 0)) # NOTE : 각 열에 6보다 작은 값의 갯수

7
7
[3 1 3]
[2 1 2 2]


In [53]:
print(np.any(np.greater(x, 8))) # NOTE : 8보다 큰 수가 있는가?
print(np.all(np.less(x, 10))) # NOTE : 모든 값이 10보다 작은가?
print(np.all(np.less(x, 8), axis = 1)) # NOTE : 각 행의 모든 값이 8보다 작은가?

True
True
[ True False  True]


In [18]:
# NOTE : bool 연산자와 대응 ufunc
# & : np.bitwise_and
# | : np.bitwise_or
# ^ : np.bitwise_xor
# ~ : np.bitwise_not

In [48]:
# NOTE : 강수량이 0.5인치에서 1인치 사이인 날
print(np.sum((inches > 0.5) & (inches < 1)))
print(np.sum(~((inches <= 0.5) | (1 <= inches))))

29
29


In [56]:
# NOTE : 마스킹 연산
# 마스킹 연산 : 배열에서 조건에 맞는 값들을 선택

x[x < 5]
# output : array([4, 1, 2, 2, 1, 3])
# NOTE : 마스크 배열이 True인 위치에 있는 모든 값으로 채워짐.

array([4, 1, 2, 2, 1, 3])