In [3]:
import numpy as np

In [5]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [9]:
grid = np.arange(16).reshape(4,4)

# NOTE 
# np.vsplit : 수평으로 분할, np.hsplit : 수직으로 분할
upper, lower = np.vsplit(grid, [2])
print(upper,'\n \n', lower)

[[0 1 2 3]
 [4 5 6 7]] 
 
 [[ 8  9 10 11]
 [12 13 14 15]]


In [10]:
left, right = np.hsplit(grid, [2])
print(left, '\n\n', right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]] 

 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
