In [14]:
import numpy as np

# NOTE
# NumPy의 배열 연산은 아주 빠르거나 아주 느릴수 있는데, 이 연산을 빠르게 만드는 핵심은 바로 벡터화연산을 사용하는 것이다.
# 그것은 일반적으로 NumPy의 Universal Functions(ufuncs)를 통해 구현된다.

# NOTE : UFuncs에는 단일 입력값에 동작하는 단항 ufuncs, 두 개의 입력값에 동작하는 이항 ufuncs가 있다.

In [2]:
x = np.arange(4)

# NOTE : 배열 산술연산
print("x    = ", x)
print("x+5  = ", x + 5)
print("x-5  = ", x - 5)
print("x*2  = ", x * 2)
print("x/2  = ", x / 2)
print("x//2 = ", x // 2) # NOTE : 바닥 나눗셈(나머지는 버림)
print("-x   = ", -x)
print("x^2  = ", x**2)
print("x%2  = ", x % 2)

x    =  [0 1 2 3]
x+5  =  [5 6 7 8]
x-5  =  [-5 -4 -3 -2]
x*2  =  [0 2 4 6]
x/2  =  [0.  0.5 1.  1.5]
x//2 =  [0 0 1 1]
-x   =  [ 0 -1 -2 -3]
x^2  =  [0 1 4 9]
x%2  =  [0 1 0 1]


In [3]:
print("x   = ", x)
print("x+5 = ", np.add(x, 5))
print("x-5 = ", np.subtract(x, 5))
print("x*2 = ", np.multiply(x, 2))
print("x/2 = ", np.divide(x, 2))
print("x//2 = ", np.floor_divide(x, 2))
print("-x  = ", -x)
print("x^2 = ", np.power(x, 2))
print("x%2 = ", np.mod(x, 2))

x   =  [0 1 2 3]
x+5 =  [5 6 7 8]
x-5 =  [-5 -4 -3 -2]
x*2 =  [0 2 4 6]
x/2 =  [0.  0.5 1.  1.5]
x//2 =  [0 0 1 1]
-x  =  [ 0 -1 -2 -3]
x^2 =  [0 1 4 9]
x%2 =  [0 1 0 1]


In [7]:
# NOTE : 절댓값 함수
x = np.array([-2, -1, 0, 1, 2])
y = np.array([3-4j, 4-3j, 2+0j, 0+1j])

print(abs(x))
print(np.abs(x))
print(np.absolute(x))

print(abs(y))
print(np.abs(y))
print(np.absolute(y))

[2 1 0 1 2]
[2 1 0 1 2]
[2 1 0 1 2]
[5. 5. 2. 1.]
[5. 5. 2. 1.]
[5. 5. 2. 1.]


In [10]:
# NOTE : 삼각함수
theta = np.linspace(0, np.pi, 3) # NOTE : 0부터 pi까지 균등하게 3개의 원소로 구성된 배열을 만듦.
print("theta   = ", theta)
print("sin(theta)  = ", np.sin(theta))
print("cos(theta)  = ", np.cos(theta))
print("tan(theta   = ", np.tan(theta))
print('\n')

x = [-1, 0, 1]
print("x   = ", x)
print("arcsin(x)   = ", np.arcsin(x))
print("arccos(x)   = ", np.arccos(x))
print("arctan(x)   = ", np.arctan(x))

theta   =  [0.         1.57079633 3.14159265]
sin(theta)  =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta)  =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta   =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


x   =  [-1, 0, 1]
arcsin(x)   =  [-1.57079633  0.          1.57079633]
arccos(x)   =  [3.14159265 1.57079633 0.        ]
arctan(x)   =  [-0.78539816  0.          0.78539816]


In [13]:
# NOTE : 지수와 로그함수
x = [1, 2, 3]
print("x   = ", x)
print("e^x = ", np.exp(x))
print("2^x = ", np.exp2(x))
print("3^x = ", np.power(3,x))
print('\n')

x = [1, 2, 4, 10]
print("x   = ", x)
print("ln(x)    = ", np.log(x))
print("log2(x)  = ", np.log2(x))
print("log10(x) = ", np.log10(x))
print('\n')

# NOTE : 매우 작은 입력값의 정확도 유지
x = [0, 0.001, 0.01, 0.1]
print('exp(x) - 1    = ', np.expm1(x))
print('log(x + 1)    = ', np.log1p(x))

x   =  [1, 2, 3]
e^x =  [ 2.71828183  7.3890561  20.08553692]
2^x =  [2. 4. 8.]
3^x =  [ 3  9 27]


x   =  [1, 2, 4, 10]
ln(x)    =  [0.         0.69314718 1.38629436 2.30258509]
log2(x)  =  [0.         1.         2.         3.32192809]
log10(x) =  [0.         0.30103    0.60205999 1.        ]


exp(x) - 1    =  [0.         0.0010005  0.01005017 0.10517092]
log(x + 1)    =  [0.         0.0009995  0.00995033 0.09531018]
