In [1]:
import numpy as np

In [2]:
# NOTE : 객체로부터 직접 연산할 수 있는 집계 함수

x = np.arange(1, 6) 
print(np.add.reduce(x)) # NOTE : 배열의 모든 요소의 합 반환
print(np.multiply.reduce(x)) # NOTE : 배열의 모든 요소의 곱 반환


print(np.add.accumulate(x)) # NOTE : 계산의 중간 결과를 모두 저장
print(np.multiply.accumulate(x))

15
120
[ 1  3  6 10 15]
[  1   2   6  24 120]


In [4]:
# NOTE : 외적(Outer products)
x = np.arange(1, 6)
np.multiply.outer(x, x)

[1 2 3 4 5]


array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])