In [1]:
import numpy as np

In [6]:
M = np.random.random((3, 4))
print(M)
M.sum()

[[0.55582201 0.62720641 0.15878582 0.97212603]
 [0.92341298 0.42881043 0.19536175 0.97537511]
 [0.19206812 0.17953433 0.0780352  0.29737519]]


5.583913365815409

In [8]:
# NOTE : (열) axis = 0, (행) axis = 1
print(M.min(axis=0))
print(M.min(axis=1))

[0.19206812 0.17953433 0.0780352  0.29737519]
[0.15878582 0.19536175 0.0780352 ]


In [9]:
# NOTE : ufunc으로서의 비교 연산자
x = np.array([1, 2, 3, 4, 5])
x < 3

array([ True,  True, False, False, False])