In [2]:
# -*- coding : utf-8 -*-

import numpy as np

In [ ]:
# NOTE
# 벡터화하는 연산을 위해서는 NumPy의 ufuncs말고 브로드캐스팅 기능이 있다.
# 브로드캐스팅은 다른 크기의 배열에 이항 ufuncs를 적용하기 위한 규칙이다.

In [5]:
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
print(a + b)
print(a + 5)

[5 6 7]
[5 6 7]


In [7]:
M = np.ones((3,3))
M + a

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [11]:
a2 = np.arange(3)
b2 = np.arange(3)[:, np.newaxis]
print(a2, b2)
a2 + b2

[0 1 2] [[0]
 [1]
 [2]]


array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [ ]:
# NOTE
# 브로드캐스팅 규칙
# 1. 두 배열의 차원 수가 다르면 더 작은 수의 차원을 가진 배열 형상의 앞쪽(왼쪽)을 1로 채운다.
# 2. 두 배열의 형상이 어떤 차원에서도 일치하지 않는다면 해당 차원의 형상이 1인 배열이 다른 형상과 일치하도록 늘어난다.
# 3. 임의의 차원에서 크기가 일치하지 않고 1도 아니라면 오류가 발생한다.

array([[0, 1, 2]])

In [23]:
M + a

array([[1., 2., 3.],
       [1., 2., 3.]])

In [24]:
# Ex.
M = np.ones((2, 3))
a = np.arange(3)

# step.1
# M.shape = (2, 3)
# a.shape = (3, )

# step.2
# M.shape = (2, 3)
# a.shape = (1, 3)

# step.3
# M.shape = (2, 3)
# a.shape = (2, 3)

M + a

array([[1., 2., 3.],
       [1., 2., 3.]])